//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//


package com.arma.uetds_boot.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.arma.uetds_boot.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IptalTurleri_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "iptalTurleri");
    private final static QName _IptalTurleriResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "iptalTurleriResponse");
    private final static QName _ParamTehlikeliMaddeTasimaSekli_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "paramTehlikeliMaddeTasimaSekli");
    private final static QName _ParamTehlikeliMaddeTasimaSekliResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "paramTehlikeliMaddeTasimaSekliResponse");
    private final static QName _ParamYukBirimi_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "paramYukBirimi");
    private final static QName _ParamYukBirimiResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "paramYukBirimiResponse");
    private final static QName _ParamYukTuru_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "paramYukTuru");
    private final static QName _ParamYukTuruResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "paramYukTuruResponse");
    private final static QName _ServisTest_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "servisTest");
    private final static QName _ServisTestResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "servisTestResponse");
    private final static QName _YeniYukKaydiBildir_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yeniYukKaydiBildir");
    private final static QName _YeniYukKaydiBildirResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yeniYukKaydiBildirResponse");
    private final static QName _YukBildirimRaporu_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimRaporu");
    private final static QName _YukBildirimRaporuResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimRaporuResponse");
    private final static QName _YukBildirimiDetayi_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiDetayi");
    private final static QName _YukBildirimiDetayiResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiDetayiResponse");
    private final static QName _YukBildirimiGuncelle_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiGuncelle");
    private final static QName _YukBildirimiGuncelleResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiGuncelleResponse");
    private final static QName _YukBildirimiIptalEt_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiIptalEt");
    private final static QName _YukBildirimiIptalEtResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiIptalEtResponse");
    private final static QName _YukBildirimiListesi_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiListesi");
    private final static QName _YukBildirimiListesiResponse_QNAME = new QName("http://uetds.unetws.udhb.gov.tr/", "yukBildirimiListesiResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.arma.uetds_boot.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IptalTurleri }
     * 
     */
    public IptalTurleri createIptalTurleri() {
        return new IptalTurleri();
    }

    /**
     * Create an instance of {@link IptalTurleriResponse }
     * 
     */
    public IptalTurleriResponse createIptalTurleriResponse() {
        return new IptalTurleriResponse();
    }

    /**
     * Create an instance of {@link ParamTehlikeliMaddeTasimaSekli }
     * 
     */
    public ParamTehlikeliMaddeTasimaSekli createParamTehlikeliMaddeTasimaSekli() {
        return new ParamTehlikeliMaddeTasimaSekli();
    }

    /**
     * Create an instance of {@link ParamTehlikeliMaddeTasimaSekliResponse }
     * 
     */
    public ParamTehlikeliMaddeTasimaSekliResponse createParamTehlikeliMaddeTasimaSekliResponse() {
        return new ParamTehlikeliMaddeTasimaSekliResponse();
    }

    /**
     * Create an instance of {@link ParamYukBirimi }
     * 
     */
    public ParamYukBirimi createParamYukBirimi() {
        return new ParamYukBirimi();
    }

    /**
     * Create an instance of {@link ParamYukBirimiResponse }
     * 
     */
    public ParamYukBirimiResponse createParamYukBirimiResponse() {
        return new ParamYukBirimiResponse();
    }

    /**
     * Create an instance of {@link ParamYukTuru }
     * 
     */
    public ParamYukTuru createParamYukTuru() {
        return new ParamYukTuru();
    }

    /**
     * Create an instance of {@link ParamYukTuruResponse }
     * 
     */
    public ParamYukTuruResponse createParamYukTuruResponse() {
        return new ParamYukTuruResponse();
    }

    /**
     * Create an instance of {@link ServisTest }
     * 
     */
    public ServisTest createServisTest() {
        return new ServisTest();
    }

    /**
     * Create an instance of {@link ServisTestResponse }
     * 
     */
    public ServisTestResponse createServisTestResponse() {
        return new ServisTestResponse();
    }

    /**
     * Create an instance of {@link YeniYukKaydiBildir }
     * 
     */
    public YeniYukKaydiBildir createYeniYukKaydiBildir() {
        return new YeniYukKaydiBildir();
    }

    /**
     * Create an instance of {@link YeniYukKaydiBildirResponse }
     * 
     */
    public YeniYukKaydiBildirResponse createYeniYukKaydiBildirResponse() {
        return new YeniYukKaydiBildirResponse();
    }

    /**
     * Create an instance of {@link YukBildirimRaporu }
     * 
     */
    public YukBildirimRaporu createYukBildirimRaporu() {
        return new YukBildirimRaporu();
    }

    /**
     * Create an instance of {@link YukBildirimRaporuResponse }
     * 
     */
    public YukBildirimRaporuResponse createYukBildirimRaporuResponse() {
        return new YukBildirimRaporuResponse();
    }

    /**
     * Create an instance of {@link YukBildirimiDetayi }
     * 
     */
    public YukBildirimiDetayi createYukBildirimiDetayi() {
        return new YukBildirimiDetayi();
    }

    /**
     * Create an instance of {@link YukBildirimiDetayiResponse }
     * 
     */
    public YukBildirimiDetayiResponse createYukBildirimiDetayiResponse() {
        return new YukBildirimiDetayiResponse();
    }

    /**
     * Create an instance of {@link YukBildirimiGuncelle }
     * 
     */
    public YukBildirimiGuncelle createYukBildirimiGuncelle() {
        return new YukBildirimiGuncelle();
    }

    /**
     * Create an instance of {@link YukBildirimiGuncelleResponse }
     * 
     */
    public YukBildirimiGuncelleResponse createYukBildirimiGuncelleResponse() {
        return new YukBildirimiGuncelleResponse();
    }

    /**
     * Create an instance of {@link YukBildirimiIptalEt }
     * 
     */
    public YukBildirimiIptalEt createYukBildirimiIptalEt() {
        return new YukBildirimiIptalEt();
    }

    /**
     * Create an instance of {@link YukBildirimiIptalEtResponse }
     * 
     */
    public YukBildirimiIptalEtResponse createYukBildirimiIptalEtResponse() {
        return new YukBildirimiIptalEtResponse();
    }

    /**
     * Create an instance of {@link YukBildirimiListesi }
     * 
     */
    public YukBildirimiListesi createYukBildirimiListesi() {
        return new YukBildirimiListesi();
    }

    /**
     * Create an instance of {@link YukBildirimiListesiResponse }
     * 
     */
    public YukBildirimiListesiResponse createYukBildirimiListesiResponse() {
        return new YukBildirimiListesiResponse();
    }

    /**
     * Create an instance of {@link UetdsYtsUser }
     * 
     */
    public UetdsYtsUser createUetdsYtsUser() {
        return new UetdsYtsUser();
    }

    /**
     * Create an instance of {@link WsUetdsEsyaAracBilgileriInput }
     * 
     */
    public WsUetdsEsyaAracBilgileriInput createWsUetdsEsyaAracBilgileriInput() {
        return new WsUetdsEsyaAracBilgileriInput();
    }

    /**
     * Create an instance of {@link WsUetdsEsyaYukBilgileriInput }
     * 
     */
    public WsUetdsEsyaYukBilgileriInput createWsUetdsEsyaYukBilgileriInput() {
        return new WsUetdsEsyaYukBilgileriInput();
    }

    /**
     * Create an instance of {@link UetdsEsyaYeniYukKaydiBildirSonuc }
     * 
     */
    public UetdsEsyaYeniYukKaydiBildirSonuc createUetdsEsyaYeniYukKaydiBildirSonuc() {
        return new UetdsEsyaYeniYukKaydiBildirSonuc();
    }

    /**
     * Create an instance of {@link UetdsEsyaSonuc }
     * 
     */
    public UetdsEsyaSonuc createUetdsEsyaSonuc() {
        return new UetdsEsyaSonuc();
    }

    /**
     * Create an instance of {@link UetdsEsyaParamIptalTuruSonuc }
     * 
     */
    public UetdsEsyaParamIptalTuruSonuc createUetdsEsyaParamIptalTuruSonuc() {
        return new UetdsEsyaParamIptalTuruSonuc();
    }

    /**
     * Create an instance of {@link ParamIptalTurListesi }
     * 
     */
    public ParamIptalTurListesi createParamIptalTurListesi() {
        return new ParamIptalTurListesi();
    }

    /**
     * Create an instance of {@link UetdsEsyaParamYukBirimiSonuc }
     * 
     */
    public UetdsEsyaParamYukBirimiSonuc createUetdsEsyaParamYukBirimiSonuc() {
        return new UetdsEsyaParamYukBirimiSonuc();
    }

    /**
     * Create an instance of {@link ParamYukBirimiListesi }
     * 
     */
    public ParamYukBirimiListesi createParamYukBirimiListesi() {
        return new ParamYukBirimiListesi();
    }

    /**
     * Create an instance of {@link UetdsEsyaParamEsyaTurSonuc }
     * 
     */
    public UetdsEsyaParamEsyaTurSonuc createUetdsEsyaParamEsyaTurSonuc() {
        return new UetdsEsyaParamEsyaTurSonuc();
    }

    /**
     * Create an instance of {@link ParamEsyaTurListesi }
     * 
     */
    public ParamEsyaTurListesi createParamEsyaTurListesi() {
        return new ParamEsyaTurListesi();
    }

    /**
     * Create an instance of {@link UetdsEsyaParamTehlikeliMaddeTasimaSekliSonuc }
     * 
     */
    public UetdsEsyaParamTehlikeliMaddeTasimaSekliSonuc createUetdsEsyaParamTehlikeliMaddeTasimaSekliSonuc() {
        return new UetdsEsyaParamTehlikeliMaddeTasimaSekliSonuc();
    }

    /**
     * Create an instance of {@link CstParamEsyaTehlikeliMaddeTasimaSekli }
     * 
     */
    public CstParamEsyaTehlikeliMaddeTasimaSekli createCstParamEsyaTehlikeliMaddeTasimaSekli() {
        return new CstParamEsyaTehlikeliMaddeTasimaSekli();
    }

    /**
     * Create an instance of {@link UetdsEsyaWsBildirimListesiSonuc }
     * 
     */
    public UetdsEsyaWsBildirimListesiSonuc createUetdsEsyaWsBildirimListesiSonuc() {
        return new UetdsEsyaWsBildirimListesiSonuc();
    }

    /**
     * Create an instance of {@link WsYukBildirimiListesi }
     * 
     */
    public WsYukBildirimiListesi createWsYukBildirimiListesi() {
        return new WsYukBildirimiListesi();
    }

    /**
     * Create an instance of {@link UetdsGenelPdfSonuc }
     * 
     */
    public UetdsGenelPdfSonuc createUetdsGenelPdfSonuc() {
        return new UetdsGenelPdfSonuc();
    }

    /**
     * Create an instance of {@link UetdsEsyaWsYukBildirimDetayiSonuc }
     * 
     */
    public UetdsEsyaWsYukBildirimDetayiSonuc createUetdsEsyaWsYukBildirimDetayiSonuc() {
        return new UetdsEsyaWsYukBildirimDetayiSonuc();
    }

    /**
     * Create an instance of {@link WsYukBildirimDetayi }
     * 
     */
    public WsYukBildirimDetayi createWsYukBildirimDetayi() {
        return new WsYukBildirimDetayi();
    }

    /**
     * Create an instance of {@link UetdsGenelIslemSonuc }
     * 
     */
    public UetdsGenelIslemSonuc createUetdsGenelIslemSonuc() {
        return new UetdsGenelIslemSonuc();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IptalTurleri }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IptalTurleri }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "iptalTurleri")
    public JAXBElement<IptalTurleri> createIptalTurleri(IptalTurleri value) {
        return new JAXBElement<IptalTurleri>(_IptalTurleri_QNAME, IptalTurleri.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IptalTurleriResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IptalTurleriResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "iptalTurleriResponse")
    public JAXBElement<IptalTurleriResponse> createIptalTurleriResponse(IptalTurleriResponse value) {
        return new JAXBElement<IptalTurleriResponse>(_IptalTurleriResponse_QNAME, IptalTurleriResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamTehlikeliMaddeTasimaSekli }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParamTehlikeliMaddeTasimaSekli }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "paramTehlikeliMaddeTasimaSekli")
    public JAXBElement<ParamTehlikeliMaddeTasimaSekli> createParamTehlikeliMaddeTasimaSekli(ParamTehlikeliMaddeTasimaSekli value) {
        return new JAXBElement<ParamTehlikeliMaddeTasimaSekli>(_ParamTehlikeliMaddeTasimaSekli_QNAME, ParamTehlikeliMaddeTasimaSekli.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamTehlikeliMaddeTasimaSekliResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParamTehlikeliMaddeTasimaSekliResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "paramTehlikeliMaddeTasimaSekliResponse")
    public JAXBElement<ParamTehlikeliMaddeTasimaSekliResponse> createParamTehlikeliMaddeTasimaSekliResponse(ParamTehlikeliMaddeTasimaSekliResponse value) {
        return new JAXBElement<ParamTehlikeliMaddeTasimaSekliResponse>(_ParamTehlikeliMaddeTasimaSekliResponse_QNAME, ParamTehlikeliMaddeTasimaSekliResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamYukBirimi }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParamYukBirimi }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "paramYukBirimi")
    public JAXBElement<ParamYukBirimi> createParamYukBirimi(ParamYukBirimi value) {
        return new JAXBElement<ParamYukBirimi>(_ParamYukBirimi_QNAME, ParamYukBirimi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamYukBirimiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParamYukBirimiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "paramYukBirimiResponse")
    public JAXBElement<ParamYukBirimiResponse> createParamYukBirimiResponse(ParamYukBirimiResponse value) {
        return new JAXBElement<ParamYukBirimiResponse>(_ParamYukBirimiResponse_QNAME, ParamYukBirimiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamYukTuru }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParamYukTuru }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "paramYukTuru")
    public JAXBElement<ParamYukTuru> createParamYukTuru(ParamYukTuru value) {
        return new JAXBElement<ParamYukTuru>(_ParamYukTuru_QNAME, ParamYukTuru.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamYukTuruResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParamYukTuruResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "paramYukTuruResponse")
    public JAXBElement<ParamYukTuruResponse> createParamYukTuruResponse(ParamYukTuruResponse value) {
        return new JAXBElement<ParamYukTuruResponse>(_ParamYukTuruResponse_QNAME, ParamYukTuruResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServisTest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ServisTest }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "servisTest")
    public JAXBElement<ServisTest> createServisTest(ServisTest value) {
        return new JAXBElement<ServisTest>(_ServisTest_QNAME, ServisTest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServisTestResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ServisTestResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "servisTestResponse")
    public JAXBElement<ServisTestResponse> createServisTestResponse(ServisTestResponse value) {
        return new JAXBElement<ServisTestResponse>(_ServisTestResponse_QNAME, ServisTestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YeniYukKaydiBildir }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YeniYukKaydiBildir }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yeniYukKaydiBildir")
    public JAXBElement<YeniYukKaydiBildir> createYeniYukKaydiBildir(YeniYukKaydiBildir value) {
        return new JAXBElement<YeniYukKaydiBildir>(_YeniYukKaydiBildir_QNAME, YeniYukKaydiBildir.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YeniYukKaydiBildirResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YeniYukKaydiBildirResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yeniYukKaydiBildirResponse")
    public JAXBElement<YeniYukKaydiBildirResponse> createYeniYukKaydiBildirResponse(YeniYukKaydiBildirResponse value) {
        return new JAXBElement<YeniYukKaydiBildirResponse>(_YeniYukKaydiBildirResponse_QNAME, YeniYukKaydiBildirResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimRaporu }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimRaporu }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimRaporu")
    public JAXBElement<YukBildirimRaporu> createYukBildirimRaporu(YukBildirimRaporu value) {
        return new JAXBElement<YukBildirimRaporu>(_YukBildirimRaporu_QNAME, YukBildirimRaporu.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimRaporuResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimRaporuResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimRaporuResponse")
    public JAXBElement<YukBildirimRaporuResponse> createYukBildirimRaporuResponse(YukBildirimRaporuResponse value) {
        return new JAXBElement<YukBildirimRaporuResponse>(_YukBildirimRaporuResponse_QNAME, YukBildirimRaporuResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiDetayi }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiDetayi }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiDetayi")
    public JAXBElement<YukBildirimiDetayi> createYukBildirimiDetayi(YukBildirimiDetayi value) {
        return new JAXBElement<YukBildirimiDetayi>(_YukBildirimiDetayi_QNAME, YukBildirimiDetayi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiDetayiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiDetayiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiDetayiResponse")
    public JAXBElement<YukBildirimiDetayiResponse> createYukBildirimiDetayiResponse(YukBildirimiDetayiResponse value) {
        return new JAXBElement<YukBildirimiDetayiResponse>(_YukBildirimiDetayiResponse_QNAME, YukBildirimiDetayiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiGuncelle }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiGuncelle }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiGuncelle")
    public JAXBElement<YukBildirimiGuncelle> createYukBildirimiGuncelle(YukBildirimiGuncelle value) {
        return new JAXBElement<YukBildirimiGuncelle>(_YukBildirimiGuncelle_QNAME, YukBildirimiGuncelle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiGuncelleResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiGuncelleResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiGuncelleResponse")
    public JAXBElement<YukBildirimiGuncelleResponse> createYukBildirimiGuncelleResponse(YukBildirimiGuncelleResponse value) {
        return new JAXBElement<YukBildirimiGuncelleResponse>(_YukBildirimiGuncelleResponse_QNAME, YukBildirimiGuncelleResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiIptalEt }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiIptalEt }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiIptalEt")
    public JAXBElement<YukBildirimiIptalEt> createYukBildirimiIptalEt(YukBildirimiIptalEt value) {
        return new JAXBElement<YukBildirimiIptalEt>(_YukBildirimiIptalEt_QNAME, YukBildirimiIptalEt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiIptalEtResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiIptalEtResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiIptalEtResponse")
    public JAXBElement<YukBildirimiIptalEtResponse> createYukBildirimiIptalEtResponse(YukBildirimiIptalEtResponse value) {
        return new JAXBElement<YukBildirimiIptalEtResponse>(_YukBildirimiIptalEtResponse_QNAME, YukBildirimiIptalEtResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiListesi }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiListesi }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiListesi")
    public JAXBElement<YukBildirimiListesi> createYukBildirimiListesi(YukBildirimiListesi value) {
        return new JAXBElement<YukBildirimiListesi>(_YukBildirimiListesi_QNAME, YukBildirimiListesi.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link YukBildirimiListesiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link YukBildirimiListesiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://uetds.unetws.udhb.gov.tr/", name = "yukBildirimiListesiResponse")
    public JAXBElement<YukBildirimiListesiResponse> createYukBildirimiListesiResponse(YukBildirimiListesiResponse value) {
        return new JAXBElement<YukBildirimiListesiResponse>(_YukBildirimiListesiResponse_QNAME, YukBildirimiListesiResponse.class, null, value);
    }

}
