//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uetds.unetws.udhb.gov.tr/")
package com.arma.uetds_boot.wsdl;
