//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//


package com.arma.uetds_boot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsUetdsEsyaAracBilgileriInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsUetdsEsyaAracBilgileriInput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="plaka1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="plaka2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sofor1TcNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sofor2TcNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tasimaTuruKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsUetdsEsyaAracBilgileriInput", propOrder = {
    "plaka1",
    "plaka2",
    "sofor1TcNo",
    "sofor2TcNo",
    "tasimaTuruKodu"
})
public class WsUetdsEsyaAracBilgileriInput {

    @XmlElement(required = true)
    protected String plaka1;
    protected String plaka2;
    protected String sofor1TcNo;
    protected String sofor2TcNo;
    protected String tasimaTuruKodu;

    /**
     * Gets the value of the plaka1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaka1() {
        return plaka1;
    }

    /**
     * Sets the value of the plaka1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaka1(String value) {
        this.plaka1 = value;
    }

    /**
     * Gets the value of the plaka2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaka2() {
        return plaka2;
    }

    /**
     * Sets the value of the plaka2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaka2(String value) {
        this.plaka2 = value;
    }

    /**
     * Gets the value of the sofor1TcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSofor1TcNo() {
        return sofor1TcNo;
    }

    /**
     * Sets the value of the sofor1TcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSofor1TcNo(String value) {
        this.sofor1TcNo = value;
    }

    /**
     * Gets the value of the sofor2TcNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSofor2TcNo() {
        return sofor2TcNo;
    }

    /**
     * Sets the value of the sofor2TcNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSofor2TcNo(String value) {
        this.sofor2TcNo = value;
    }

    /**
     * Gets the value of the tasimaTuruKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasimaTuruKodu() {
        return tasimaTuruKodu;
    }

    /**
     * Sets the value of the tasimaTuruKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasimaTuruKodu(String value) {
        this.tasimaTuruKodu = value;
    }

}
