//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//


package com.arma.uetds_boot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsUetdsEsyaYukBilgileriInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsUetdsEsyaYukBilgileriInput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gonderenVergiNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gonderenUnvan" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="aliciVergiNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="aliciUnvan" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yuklemeUlkeKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yuklemeIlMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yuklemeIlceMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bosaltmaUlkeKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bosaltmaIlMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bosaltmaIlceMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yuklemeTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yuklemeSaati" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bosaltmaTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bosaltmaSaati" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yukCinsId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yukBirimi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="yukMiktari" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tasimaBedeli" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="unNumarasi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tehlikeliMaddeTasimaSekli" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsUetdsEsyaYukBilgileriInput", propOrder = {
    "gonderenVergiNo",
    "gonderenUnvan",
    "aliciVergiNo",
    "aliciUnvan",
    "yuklemeUlkeKodu",
    "yuklemeIlMernisKodu",
    "yuklemeIlceMernisKodu",
    "bosaltmaUlkeKodu",
    "bosaltmaIlMernisKodu",
    "bosaltmaIlceMernisKodu",
    "yuklemeTarihi",
    "yuklemeSaati",
    "bosaltmaTarihi",
    "bosaltmaSaati",
    "yukCinsId",
    "yukBirimi",
    "yukMiktari",
    "tasimaBedeli",
    "unNumarasi",
    "tehlikeliMaddeTasimaSekli"
})
public class WsUetdsEsyaYukBilgileriInput {

    protected String gonderenVergiNo;
    @XmlElement(required = true)
    protected String gonderenUnvan;
    protected String aliciVergiNo;
    @XmlElement(required = true)
    protected String aliciUnvan;
    @XmlElement(required = true)
    protected String yuklemeUlkeKodu;
    @XmlElement(required = true)
    protected String yuklemeIlMernisKodu;
    @XmlElement(required = true)
    protected String yuklemeIlceMernisKodu;
    @XmlElement(required = true)
    protected String bosaltmaUlkeKodu;
    @XmlElement(required = true)
    protected String bosaltmaIlMernisKodu;
    @XmlElement(required = true)
    protected String bosaltmaIlceMernisKodu;
    @XmlElement(required = true)
    protected String yuklemeTarihi;
    @XmlElement(required = true)
    protected String yuklemeSaati;
    @XmlElement(required = true)
    protected String bosaltmaTarihi;
    @XmlElement(required = true)
    protected String bosaltmaSaati;
    @XmlElement(required = true)
    protected String yukCinsId;
    @XmlElement(required = true)
    protected String yukBirimi;
    @XmlElement(required = true)
    protected String yukMiktari;
    @XmlElement(required = true)
    protected String tasimaBedeli;
    protected String unNumarasi;
    protected String tehlikeliMaddeTasimaSekli;

    /**
     * Gets the value of the gonderenVergiNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGonderenVergiNo() {
        return gonderenVergiNo;
    }

    /**
     * Sets the value of the gonderenVergiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGonderenVergiNo(String value) {
        this.gonderenVergiNo = value;
    }

    /**
     * Gets the value of the gonderenUnvan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGonderenUnvan() {
        return gonderenUnvan;
    }

    /**
     * Sets the value of the gonderenUnvan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGonderenUnvan(String value) {
        this.gonderenUnvan = value;
    }

    /**
     * Gets the value of the aliciVergiNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliciVergiNo() {
        return aliciVergiNo;
    }

    /**
     * Sets the value of the aliciVergiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliciVergiNo(String value) {
        this.aliciVergiNo = value;
    }

    /**
     * Gets the value of the aliciUnvan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliciUnvan() {
        return aliciUnvan;
    }

    /**
     * Sets the value of the aliciUnvan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliciUnvan(String value) {
        this.aliciUnvan = value;
    }

    /**
     * Gets the value of the yuklemeUlkeKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeUlkeKodu() {
        return yuklemeUlkeKodu;
    }

    /**
     * Sets the value of the yuklemeUlkeKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeUlkeKodu(String value) {
        this.yuklemeUlkeKodu = value;
    }

    /**
     * Gets the value of the yuklemeIlMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeIlMernisKodu() {
        return yuklemeIlMernisKodu;
    }

    /**
     * Sets the value of the yuklemeIlMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeIlMernisKodu(String value) {
        this.yuklemeIlMernisKodu = value;
    }

    /**
     * Gets the value of the yuklemeIlceMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeIlceMernisKodu() {
        return yuklemeIlceMernisKodu;
    }

    /**
     * Sets the value of the yuklemeIlceMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeIlceMernisKodu(String value) {
        this.yuklemeIlceMernisKodu = value;
    }

    /**
     * Gets the value of the bosaltmaUlkeKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaUlkeKodu() {
        return bosaltmaUlkeKodu;
    }

    /**
     * Sets the value of the bosaltmaUlkeKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaUlkeKodu(String value) {
        this.bosaltmaUlkeKodu = value;
    }

    /**
     * Gets the value of the bosaltmaIlMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaIlMernisKodu() {
        return bosaltmaIlMernisKodu;
    }

    /**
     * Sets the value of the bosaltmaIlMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaIlMernisKodu(String value) {
        this.bosaltmaIlMernisKodu = value;
    }

    /**
     * Gets the value of the bosaltmaIlceMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaIlceMernisKodu() {
        return bosaltmaIlceMernisKodu;
    }

    /**
     * Sets the value of the bosaltmaIlceMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaIlceMernisKodu(String value) {
        this.bosaltmaIlceMernisKodu = value;
    }

    /**
     * Gets the value of the yuklemeTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeTarihi() {
        return yuklemeTarihi;
    }

    /**
     * Sets the value of the yuklemeTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeTarihi(String value) {
        this.yuklemeTarihi = value;
    }

    /**
     * Gets the value of the yuklemeSaati property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeSaati() {
        return yuklemeSaati;
    }

    /**
     * Sets the value of the yuklemeSaati property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeSaati(String value) {
        this.yuklemeSaati = value;
    }

    /**
     * Gets the value of the bosaltmaTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaTarihi() {
        return bosaltmaTarihi;
    }

    /**
     * Sets the value of the bosaltmaTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaTarihi(String value) {
        this.bosaltmaTarihi = value;
    }

    /**
     * Gets the value of the bosaltmaSaati property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaSaati() {
        return bosaltmaSaati;
    }

    /**
     * Sets the value of the bosaltmaSaati property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaSaati(String value) {
        this.bosaltmaSaati = value;
    }

    /**
     * Gets the value of the yukCinsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukCinsId() {
        return yukCinsId;
    }

    /**
     * Sets the value of the yukCinsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukCinsId(String value) {
        this.yukCinsId = value;
    }

    /**
     * Gets the value of the yukBirimi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukBirimi() {
        return yukBirimi;
    }

    /**
     * Sets the value of the yukBirimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukBirimi(String value) {
        this.yukBirimi = value;
    }

    /**
     * Gets the value of the yukMiktari property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukMiktari() {
        return yukMiktari;
    }

    /**
     * Sets the value of the yukMiktari property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukMiktari(String value) {
        this.yukMiktari = value;
    }

    /**
     * Gets the value of the tasimaBedeli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasimaBedeli() {
        return tasimaBedeli;
    }

    /**
     * Sets the value of the tasimaBedeli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasimaBedeli(String value) {
        this.tasimaBedeli = value;
    }

    /**
     * Gets the value of the unNumarasi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnNumarasi() {
        return unNumarasi;
    }

    /**
     * Sets the value of the unNumarasi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnNumarasi(String value) {
        this.unNumarasi = value;
    }

    /**
     * Gets the value of the tehlikeliMaddeTasimaSekli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTehlikeliMaddeTasimaSekli() {
        return tehlikeliMaddeTasimaSekli;
    }

    /**
     * Sets the value of the tehlikeliMaddeTasimaSekli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTehlikeliMaddeTasimaSekli(String value) {
        this.tehlikeliMaddeTasimaSekli = value;
    }

}
