//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//


package com.arma.uetds_boot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsYukBildirimDetayi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsYukBildirimDetayi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aliciUnvan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="aliciVergiNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bildirimTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaIlAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaIlMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaIlceAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaIlceKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaSaati" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaUlkeAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bosaltmaUlkeKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="durum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gonderenUnvan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gonderenVergiNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="iptalAciklama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="iptalTurKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="plaka1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="plaka2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sofor1TCNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sofor2TCNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sonGuncellemeTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tasimaBedeli" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tasimaTuruAciklama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tasimaTuruKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tehlikeliMaddeTasimaSekliAciklama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tehlikeliMaddeTasimaSekliKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="uetdsBildirimReferansNo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="unNumarasi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yukBirimi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yukCinsAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yukCinsId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yukMiktari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeIlAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeIlMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeIlceAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeIlceMernisKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeSaati" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeUlkeAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="yuklemeUlkeKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsYukBildirimDetayi", propOrder = {
    "aliciUnvan",
    "aliciVergiNo",
    "bildirimTarihi",
    "bosaltmaIlAdi",
    "bosaltmaIlMernisKodu",
    "bosaltmaIlceAdi",
    "bosaltmaIlceKodu",
    "bosaltmaSaati",
    "bosaltmaTarihi",
    "bosaltmaUlkeAdi",
    "bosaltmaUlkeKodu",
    "durum",
    "gonderenUnvan",
    "gonderenVergiNo",
    "iptalAciklama",
    "iptalTurKodu",
    "plaka1",
    "plaka2",
    "sofor1TCNo",
    "sofor2TCNo",
    "sonGuncellemeTarihi",
    "tasimaBedeli",
    "tasimaTuruAciklama",
    "tasimaTuruKodu",
    "tehlikeliMaddeTasimaSekliAciklama",
    "tehlikeliMaddeTasimaSekliKodu",
    "uetdsBildirimReferansNo",
    "unNumarasi",
    "yukBirimi",
    "yukCinsAdi",
    "yukCinsId",
    "yukMiktari",
    "yuklemeIlAdi",
    "yuklemeIlMernisKodu",
    "yuklemeIlceAdi",
    "yuklemeIlceMernisKodu",
    "yuklemeSaati",
    "yuklemeTarihi",
    "yuklemeUlkeAdi",
    "yuklemeUlkeKodu"
})
public class WsYukBildirimDetayi {

    protected String aliciUnvan;
    protected String aliciVergiNo;
    protected String bildirimTarihi;
    protected String bosaltmaIlAdi;
    protected String bosaltmaIlMernisKodu;
    protected String bosaltmaIlceAdi;
    protected String bosaltmaIlceKodu;
    protected String bosaltmaSaati;
    protected String bosaltmaTarihi;
    protected String bosaltmaUlkeAdi;
    protected String bosaltmaUlkeKodu;
    protected String durum;
    protected String gonderenUnvan;
    protected String gonderenVergiNo;
    protected String iptalAciklama;
    protected String iptalTurKodu;
    protected String plaka1;
    protected String plaka2;
    protected String sofor1TCNo;
    protected String sofor2TCNo;
    protected String sonGuncellemeTarihi;
    protected String tasimaBedeli;
    protected String tasimaTuruAciklama;
    protected String tasimaTuruKodu;
    protected String tehlikeliMaddeTasimaSekliAciklama;
    protected String tehlikeliMaddeTasimaSekliKodu;
    protected Long uetdsBildirimReferansNo;
    protected String unNumarasi;
    protected String yukBirimi;
    protected String yukCinsAdi;
    protected String yukCinsId;
    protected String yukMiktari;
    protected String yuklemeIlAdi;
    protected String yuklemeIlMernisKodu;
    protected String yuklemeIlceAdi;
    protected String yuklemeIlceMernisKodu;
    protected String yuklemeSaati;
    protected String yuklemeTarihi;
    protected String yuklemeUlkeAdi;
    protected String yuklemeUlkeKodu;

    /**
     * Gets the value of the aliciUnvan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliciUnvan() {
        return aliciUnvan;
    }

    /**
     * Sets the value of the aliciUnvan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliciUnvan(String value) {
        this.aliciUnvan = value;
    }

    /**
     * Gets the value of the aliciVergiNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliciVergiNo() {
        return aliciVergiNo;
    }

    /**
     * Sets the value of the aliciVergiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliciVergiNo(String value) {
        this.aliciVergiNo = value;
    }

    /**
     * Gets the value of the bildirimTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBildirimTarihi() {
        return bildirimTarihi;
    }

    /**
     * Sets the value of the bildirimTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBildirimTarihi(String value) {
        this.bildirimTarihi = value;
    }

    /**
     * Gets the value of the bosaltmaIlAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaIlAdi() {
        return bosaltmaIlAdi;
    }

    /**
     * Sets the value of the bosaltmaIlAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaIlAdi(String value) {
        this.bosaltmaIlAdi = value;
    }

    /**
     * Gets the value of the bosaltmaIlMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaIlMernisKodu() {
        return bosaltmaIlMernisKodu;
    }

    /**
     * Sets the value of the bosaltmaIlMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaIlMernisKodu(String value) {
        this.bosaltmaIlMernisKodu = value;
    }

    /**
     * Gets the value of the bosaltmaIlceAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaIlceAdi() {
        return bosaltmaIlceAdi;
    }

    /**
     * Sets the value of the bosaltmaIlceAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaIlceAdi(String value) {
        this.bosaltmaIlceAdi = value;
    }

    /**
     * Gets the value of the bosaltmaIlceKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaIlceKodu() {
        return bosaltmaIlceKodu;
    }

    /**
     * Sets the value of the bosaltmaIlceKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaIlceKodu(String value) {
        this.bosaltmaIlceKodu = value;
    }

    /**
     * Gets the value of the bosaltmaSaati property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaSaati() {
        return bosaltmaSaati;
    }

    /**
     * Sets the value of the bosaltmaSaati property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaSaati(String value) {
        this.bosaltmaSaati = value;
    }

    /**
     * Gets the value of the bosaltmaTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaTarihi() {
        return bosaltmaTarihi;
    }

    /**
     * Sets the value of the bosaltmaTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaTarihi(String value) {
        this.bosaltmaTarihi = value;
    }

    /**
     * Gets the value of the bosaltmaUlkeAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaUlkeAdi() {
        return bosaltmaUlkeAdi;
    }

    /**
     * Sets the value of the bosaltmaUlkeAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaUlkeAdi(String value) {
        this.bosaltmaUlkeAdi = value;
    }

    /**
     * Gets the value of the bosaltmaUlkeKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBosaltmaUlkeKodu() {
        return bosaltmaUlkeKodu;
    }

    /**
     * Sets the value of the bosaltmaUlkeKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBosaltmaUlkeKodu(String value) {
        this.bosaltmaUlkeKodu = value;
    }

    /**
     * Gets the value of the durum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurum() {
        return durum;
    }

    /**
     * Sets the value of the durum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurum(String value) {
        this.durum = value;
    }

    /**
     * Gets the value of the gonderenUnvan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGonderenUnvan() {
        return gonderenUnvan;
    }

    /**
     * Sets the value of the gonderenUnvan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGonderenUnvan(String value) {
        this.gonderenUnvan = value;
    }

    /**
     * Gets the value of the gonderenVergiNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGonderenVergiNo() {
        return gonderenVergiNo;
    }

    /**
     * Sets the value of the gonderenVergiNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGonderenVergiNo(String value) {
        this.gonderenVergiNo = value;
    }

    /**
     * Gets the value of the iptalAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIptalAciklama() {
        return iptalAciklama;
    }

    /**
     * Sets the value of the iptalAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIptalAciklama(String value) {
        this.iptalAciklama = value;
    }

    /**
     * Gets the value of the iptalTurKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIptalTurKodu() {
        return iptalTurKodu;
    }

    /**
     * Sets the value of the iptalTurKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIptalTurKodu(String value) {
        this.iptalTurKodu = value;
    }

    /**
     * Gets the value of the plaka1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaka1() {
        return plaka1;
    }

    /**
     * Sets the value of the plaka1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaka1(String value) {
        this.plaka1 = value;
    }

    /**
     * Gets the value of the plaka2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaka2() {
        return plaka2;
    }

    /**
     * Sets the value of the plaka2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaka2(String value) {
        this.plaka2 = value;
    }

    /**
     * Gets the value of the sofor1TCNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSofor1TCNo() {
        return sofor1TCNo;
    }

    /**
     * Sets the value of the sofor1TCNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSofor1TCNo(String value) {
        this.sofor1TCNo = value;
    }

    /**
     * Gets the value of the sofor2TCNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSofor2TCNo() {
        return sofor2TCNo;
    }

    /**
     * Sets the value of the sofor2TCNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSofor2TCNo(String value) {
        this.sofor2TCNo = value;
    }

    /**
     * Gets the value of the sonGuncellemeTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonGuncellemeTarihi() {
        return sonGuncellemeTarihi;
    }

    /**
     * Sets the value of the sonGuncellemeTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonGuncellemeTarihi(String value) {
        this.sonGuncellemeTarihi = value;
    }

    /**
     * Gets the value of the tasimaBedeli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasimaBedeli() {
        return tasimaBedeli;
    }

    /**
     * Sets the value of the tasimaBedeli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasimaBedeli(String value) {
        this.tasimaBedeli = value;
    }

    /**
     * Gets the value of the tasimaTuruAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasimaTuruAciklama() {
        return tasimaTuruAciklama;
    }

    /**
     * Sets the value of the tasimaTuruAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasimaTuruAciklama(String value) {
        this.tasimaTuruAciklama = value;
    }

    /**
     * Gets the value of the tasimaTuruKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasimaTuruKodu() {
        return tasimaTuruKodu;
    }

    /**
     * Sets the value of the tasimaTuruKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasimaTuruKodu(String value) {
        this.tasimaTuruKodu = value;
    }

    /**
     * Gets the value of the tehlikeliMaddeTasimaSekliAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTehlikeliMaddeTasimaSekliAciklama() {
        return tehlikeliMaddeTasimaSekliAciklama;
    }

    /**
     * Sets the value of the tehlikeliMaddeTasimaSekliAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTehlikeliMaddeTasimaSekliAciklama(String value) {
        this.tehlikeliMaddeTasimaSekliAciklama = value;
    }

    /**
     * Gets the value of the tehlikeliMaddeTasimaSekliKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTehlikeliMaddeTasimaSekliKodu() {
        return tehlikeliMaddeTasimaSekliKodu;
    }

    /**
     * Sets the value of the tehlikeliMaddeTasimaSekliKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTehlikeliMaddeTasimaSekliKodu(String value) {
        this.tehlikeliMaddeTasimaSekliKodu = value;
    }

    /**
     * Gets the value of the uetdsBildirimReferansNo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUetdsBildirimReferansNo() {
        return uetdsBildirimReferansNo;
    }

    /**
     * Sets the value of the uetdsBildirimReferansNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUetdsBildirimReferansNo(Long value) {
        this.uetdsBildirimReferansNo = value;
    }

    /**
     * Gets the value of the unNumarasi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnNumarasi() {
        return unNumarasi;
    }

    /**
     * Sets the value of the unNumarasi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnNumarasi(String value) {
        this.unNumarasi = value;
    }

    /**
     * Gets the value of the yukBirimi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukBirimi() {
        return yukBirimi;
    }

    /**
     * Sets the value of the yukBirimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukBirimi(String value) {
        this.yukBirimi = value;
    }

    /**
     * Gets the value of the yukCinsAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukCinsAdi() {
        return yukCinsAdi;
    }

    /**
     * Sets the value of the yukCinsAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukCinsAdi(String value) {
        this.yukCinsAdi = value;
    }

    /**
     * Gets the value of the yukCinsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukCinsId() {
        return yukCinsId;
    }

    /**
     * Sets the value of the yukCinsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukCinsId(String value) {
        this.yukCinsId = value;
    }

    /**
     * Gets the value of the yukMiktari property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYukMiktari() {
        return yukMiktari;
    }

    /**
     * Sets the value of the yukMiktari property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYukMiktari(String value) {
        this.yukMiktari = value;
    }

    /**
     * Gets the value of the yuklemeIlAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeIlAdi() {
        return yuklemeIlAdi;
    }

    /**
     * Sets the value of the yuklemeIlAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeIlAdi(String value) {
        this.yuklemeIlAdi = value;
    }

    /**
     * Gets the value of the yuklemeIlMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeIlMernisKodu() {
        return yuklemeIlMernisKodu;
    }

    /**
     * Sets the value of the yuklemeIlMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeIlMernisKodu(String value) {
        this.yuklemeIlMernisKodu = value;
    }

    /**
     * Gets the value of the yuklemeIlceAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeIlceAdi() {
        return yuklemeIlceAdi;
    }

    /**
     * Sets the value of the yuklemeIlceAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeIlceAdi(String value) {
        this.yuklemeIlceAdi = value;
    }

    /**
     * Gets the value of the yuklemeIlceMernisKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeIlceMernisKodu() {
        return yuklemeIlceMernisKodu;
    }

    /**
     * Sets the value of the yuklemeIlceMernisKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeIlceMernisKodu(String value) {
        this.yuklemeIlceMernisKodu = value;
    }

    /**
     * Gets the value of the yuklemeSaati property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeSaati() {
        return yuklemeSaati;
    }

    /**
     * Sets the value of the yuklemeSaati property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeSaati(String value) {
        this.yuklemeSaati = value;
    }

    /**
     * Gets the value of the yuklemeTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeTarihi() {
        return yuklemeTarihi;
    }

    /**
     * Sets the value of the yuklemeTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeTarihi(String value) {
        this.yuklemeTarihi = value;
    }

    /**
     * Gets the value of the yuklemeUlkeAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeUlkeAdi() {
        return yuklemeUlkeAdi;
    }

    /**
     * Sets the value of the yuklemeUlkeAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeUlkeAdi(String value) {
        this.yuklemeUlkeAdi = value;
    }

    /**
     * Gets the value of the yuklemeUlkeKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYuklemeUlkeKodu() {
        return yuklemeUlkeKodu;
    }

    /**
     * Sets the value of the yuklemeUlkeKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYuklemeUlkeKodu(String value) {
        this.yuklemeUlkeKodu = value;
    }

}
