//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//


package com.arma.uetds_boot.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for yeniYukKaydiBildir complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="yeniYukKaydiBildir"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="wsuser" type="{http://uetds.unetws.udhb.gov.tr/}uetdsYtsUser"/&gt;
 *         &lt;element name="aracBilgileriInput" type="{http://uetds.unetws.udhb.gov.tr/}wsUetdsEsyaAracBilgileriInput"/&gt;
 *         &lt;element name="yukBilgileriListInput" type="{http://uetds.unetws.udhb.gov.tr/}wsUetdsEsyaYukBilgileriInput" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "yeniYukKaydiBildir", propOrder = {
    "wsuser",
    "aracBilgileriInput",
    "yukBilgileriListInput"
})
public class YeniYukKaydiBildir {

    @XmlElement(required = true)
    protected UetdsYtsUser wsuser;
    @XmlElement(required = true)
    protected WsUetdsEsyaAracBilgileriInput aracBilgileriInput;
    @XmlElement(required = true)
    protected List<WsUetdsEsyaYukBilgileriInput> yukBilgileriListInput;

    /**
     * Gets the value of the wsuser property.
     * 
     * @return
     *     possible object is
     *     {@link UetdsYtsUser }
     *     
     */
    public UetdsYtsUser getWsuser() {
        return wsuser;
    }

    /**
     * Sets the value of the wsuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link UetdsYtsUser }
     *     
     */
    public void setWsuser(UetdsYtsUser value) {
        this.wsuser = value;
    }

    /**
     * Gets the value of the aracBilgileriInput property.
     * 
     * @return
     *     possible object is
     *     {@link WsUetdsEsyaAracBilgileriInput }
     *     
     */
    public WsUetdsEsyaAracBilgileriInput getAracBilgileriInput() {
        return aracBilgileriInput;
    }

    /**
     * Sets the value of the aracBilgileriInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsUetdsEsyaAracBilgileriInput }
     *     
     */
    public void setAracBilgileriInput(WsUetdsEsyaAracBilgileriInput value) {
        this.aracBilgileriInput = value;
    }

    /**
     * Gets the value of the yukBilgileriListInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the yukBilgileriListInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getYukBilgileriListInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsUetdsEsyaYukBilgileriInput }
     * 
     * 
     */
    public List<WsUetdsEsyaYukBilgileriInput> getYukBilgileriListInput() {
        if (yukBilgileriListInput == null) {
            yukBilgileriListInput = new ArrayList<WsUetdsEsyaYukBilgileriInput>();
        }
        return this.yukBilgileriListInput;
    }

}
