//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.23 at 02:12:45 PM EET 
//


package com.arma.uetds_boot.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for yukBildirimiGuncelle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="yukBildirimiGuncelle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="wsuser" type="{http://uetds.unetws.udhb.gov.tr/}uetdsYtsUser"/&gt;
 *         &lt;element name="bildirimId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="aracBilgileriInput" type="{http://uetds.unetws.udhb.gov.tr/}wsUetdsEsyaAracBilgileriInput"/&gt;
 *         &lt;element name="yukBilgileriInput" type="{http://uetds.unetws.udhb.gov.tr/}wsUetdsEsyaYukBilgileriInput"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "yukBildirimiGuncelle", propOrder = {
    "wsuser",
    "bildirimId",
    "aracBilgileriInput",
    "yukBilgileriInput"
})
public class YukBildirimiGuncelle {

    @XmlElement(required = true)
    protected UetdsYtsUser wsuser;
    protected long bildirimId;
    @XmlElement(required = true)
    protected WsUetdsEsyaAracBilgileriInput aracBilgileriInput;
    @XmlElement(required = true)
    protected WsUetdsEsyaYukBilgileriInput yukBilgileriInput;

    /**
     * Gets the value of the wsuser property.
     * 
     * @return
     *     possible object is
     *     {@link UetdsYtsUser }
     *     
     */
    public UetdsYtsUser getWsuser() {
        return wsuser;
    }

    /**
     * Sets the value of the wsuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link UetdsYtsUser }
     *     
     */
    public void setWsuser(UetdsYtsUser value) {
        this.wsuser = value;
    }

    /**
     * Gets the value of the bildirimId property.
     * 
     */
    public long getBildirimId() {
        return bildirimId;
    }

    /**
     * Sets the value of the bildirimId property.
     * 
     */
    public void setBildirimId(long value) {
        this.bildirimId = value;
    }

    /**
     * Gets the value of the aracBilgileriInput property.
     * 
     * @return
     *     possible object is
     *     {@link WsUetdsEsyaAracBilgileriInput }
     *     
     */
    public WsUetdsEsyaAracBilgileriInput getAracBilgileriInput() {
        return aracBilgileriInput;
    }

    /**
     * Sets the value of the aracBilgileriInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsUetdsEsyaAracBilgileriInput }
     *     
     */
    public void setAracBilgileriInput(WsUetdsEsyaAracBilgileriInput value) {
        this.aracBilgileriInput = value;
    }

    /**
     * Gets the value of the yukBilgileriInput property.
     * 
     * @return
     *     possible object is
     *     {@link WsUetdsEsyaYukBilgileriInput }
     *     
     */
    public WsUetdsEsyaYukBilgileriInput getYukBilgileriInput() {
        return yukBilgileriInput;
    }

    /**
     * Sets the value of the yukBilgileriInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsUetdsEsyaYukBilgileriInput }
     *     
     */
    public void setYukBilgileriInput(WsUetdsEsyaYukBilgileriInput value) {
        this.yukBilgileriInput = value;
    }

}
